### ISSUE TITLE
Boot disk

### ISSUE THREAD

**Issue by x4080** [hackintosh-stuff/XPS9350-macOS#10]
Should i use empty acpi folder to boot to Mojave installation disk? And if keyboard and trackpad not working should i continue or solve this problem first?

Thanks

**Comment by maz-1** [comment]
Follow the guidance, leave files where they are
Trackpad may not work during installation, use usb mouse. After installation done and script executed, the kext cache will be built and things should work.

**Comment by x4080** [comment]
@maz-1 thanks for the tip, your clover is the fastest boot i found and i already tried so many, I thought that touchpad should works in installation since in high sierra it works, but with your answer im confident now, btw should i use apfs? I think my ssd is samsung pm something

Thanks again
