### ISSUE TITLE
Extremely Slow Preformance On Battery

### ISSUE THREAD

**Issue by tlefko** [hackintosh-stuff/XPS9350-macOS#13]
Hey guys, I've been working on hackintosh for a while on this device and I decided to try out your configuration

I have an i7 6560, 3K, 8GB Ram, running Mojave 10.14.1

Anyway, I have this really peculiar issue that has happened on every OS right now and I can't seem to figure out a fix. On AC power, everything runs buttery smooth and works excellent. The very second I unplug the power the speed drops to ridiculously slow and everything lags incredibly. I've been trying for days to fix this. Any help would be appreciated @maz-1

**Comment by tlefko** [comment]
Also the classic issue of black screen on wake

**Comment by tlefko** [comment]
found a solution,

**Comment by maz-1** [comment]
No such problem here, I have 10.14.6
Maybe upgrade your system or bios

**Comment by thiscodedbox** [comment]
@tlefko you didn't happen to replace your battery at some point didi you? I'm tracking down some issues on my 9350 i7-6560u that followed me from Windows 10 that resemble this. Disabling BD_PROCHOT. My slowness happens after sleep though, and shows in intel power gadget as being locked at .4GHZ or so. To fix it, I use sleepwatcher 2.2.1 to call voltageshift after wake to disable BD_PROCHOT along with reapplying my undervolt settings.

**Comment by tlefko** [comment]
> @tlefko you didn't happen to replace your battery at some point didi you? I'm tracking down some issues on my 9350 i7-6560u that followed me from Windows 10 that resemble this. Disabling BD_PROCHOT. My slowness happens after sleep though, and shows in intel power gadget as being locked at .4GHZ or so. To fix it, I use sleepwatcher 2.2.1 to call voltageshift after wake to disable BD_PROCHOT along with reapplying my undervolt settings.

yep the issue was the aftermarket battery -- replaced with original no problems. go figure
