### ISSUE TITLE
Authentication Delay

### ISSUE THREAD

**Issue by Saad-LUMS** [hackintosh-stuff/XPS9350-macOS#15]
Wherever in Settings and App Store, macOS 10.14.6 asks for authentication, it takes a long time with the loading ball cursor appearing for a few seconds both before and after authentication.
I tried syscl's deploy.sh and his config did not have this problem.
Although his led to really long boot times and no trackpad.

**Comment by maz-1** [comment]
NoTouchID.kext added.
