### ISSUE TITLE
Minimum CPU frequency is 1.3GHz on i7-6560u model, can it be smaller?

### ISSUE THREAD

**Issue by imcsq** [hackintosh-stuff/XPS9350-macOS#16]
Everything goes well on my hackintosh on XPS13-9350, i7-6560u, 8G.

The only downside is that I found that my CPU always runs at a frequency no less than 1.3GHz.

As far as I know, 6560u could run at minimum frequency of 0.4GHz. 

However, my frequency result generated by CPU-S shows that it only has 9 levels, with minimum frequency of 1.3GHz. Moreover, there are not so many levels from 1.3GHz to 2.0GHz.

That's not a big trouble. But I pardon if there is a method to lower the minimum frequency, hence to make battery last longer, and make my XPS cooler when it is on low workload (the lowest temp is about 60C...)

Thanks a lot~

![freq](https://user-images.githubusercontent.com/7814845/77603438-0e37f500-6f4b-11ea-8b27-d8384ac91ca5.png)

**Comment by maz-1** [comment]
You can read the documentation of CPUFriend to build your own power profile.

**Comment by carking** [comment]
> Everything goes well on my hackintosh on XPS13-9350, i7-6560u, 8G.
> 
> The only downside is that I found that my CPU always runs at a frequency no less than 1.3GHz.
> 
> As far as I know, 6560u could run at minimum frequency of 0.4GHz.
> 
> However, my frequency result generated by CPU-S shows that it only has 9 levels, with minimum frequency of 1.3GHz. Moreover, there are not so many levels from 1.3GHz to 2.0GHz.
> 
> That's not a big trouble. But I pardon if there is a method to lower the minimum frequency, hence to make battery last longer, and make my XPS cooler when it is on low workload (the lowest temp is about 60C...)
> 
> Thanks a lot~
> 
> ![freq](https://user-images.githubusercontent.com/7814845/77603438-0e37f500-6f4b-11ea-8b27-d8384ac91ca5.png)

这个EFI安装10.15会有莫名其妙的Bug，频率一直在2.0以上，负载下不来，安装10.14无此bug，温度和续航都很好

**Comment by imcsq** [comment]
> You can read the documentation of CPUFriend to build your own power profile.

Thanks a lot, I will have a try.
