### ISSUE TITLE
Boot from USB stuck at "AppleIntelLpssI2CController... fTimerServiceMatching timed out".

### ISSUE THREAD

**Issue by jordihoven** [hackintosh-stuff/XPS9350-macOS#17]
Followed the guide to the letter. Set verbose mode. Keep getting the above message. Tried a different USB flashdrive. Same result. 

Using a Dell XPS 9350.

**Comment by Xerz** [comment]
What Wi-Fi card do you use? If it the stock 1820A, try disabling it in UEFI settings.

**Comment by jordihoven** [comment]
Thankyou for your response. I read online that the WiFi card might be the problem. I took it out of the system and it booted fine. 
Can you mark the issue resolved by removing the WiFi card or should I?

-
Cheers,
Jordi

**Comment by Xerz** [comment]
Nice to hear.
You should mark it resolved, i cannot do that.

**Comment by jordihoven** [comment]
Removing the WiFi card (which was ofcourse unsupported) fixed the issue. I installed Mojave on my 9350 without any problems. (I am using a cheap Ethernet dongle as for now)
