### ISSUE TITLE
DW1830 Network Card

### ISSUE THREAD

**Issue by s150217754** [hackintosh-stuff/XPS9350-macOS#6]
Hello,

I have purchased a DW1830 network card as per your configuration and realised that the Bluetooth doesn't work intermittently on Battery source after waking from sleep. The Bluetooth indicator will display Not Available after a short while when there is no Bluetooth device connected to the laptop.

Just wondering whether you are facing this problem. 

By the way, the problem does not surface when it is plugged into the wall adaptor.

Thanks in advance.

**Comment by s150217754** [comment]
### *** SOLUTION BELOW ***

Hello all,

I am so close into binning this DW1830 card and getting a DW1560 as a replacement after browsing through several failed attempts on getting the DW1830 bluetooth work correctly over at [syscl's repository](https://github.com/syscl/XPS9350-macOS/issues).

I was initially thinking this issue was related to the BrcmPatch kexts. I then proceeded to switch a couple of BrcmPatch forks, and even compiling codes from both [tluck](https://github.com/tluck/OS-X-BrcmPatchRAM/) and [GridH](https://github.com/Grid-H/OS-X-BrcmPatchRAM)'s repo. Unfortunately, the bluetooth problem keeps coming back.

I have also tried increasing the Delay via boot args as stated on [RehabMan's readme](https://github.com/RehabMan/OS-X-BrcmPatchRAM/blob/master/README.md) but that doesn't seem to help much. It was a hit or miss where sometimes bluetooth gets restored well on wake, while other times the "Bluetooth Not Available" returns.

I have also tried re-attached the antennas on the card thinking it could be a loose connection.

**Solution**

After much Googling, I stumbled onto [Jay's post](https://www.tonymacx86.com/threads/bluetooth-randomly-not-available-after-sleep.266255/#post-1862126) on tonymacx86.com. The "fix" involves physically taping Pins 54 and 56 of the DW1830 WiFi Card. Since I was already on the verge to purchase a DW1560 as a replacement, I decided to give it one last go.

Turns out, taping the WiFi card is the fix to the problem and I did not get the bluetooth issue again!

For my case, I switched to [GridH's release of the BrcmPatch](https://github.com/Grid-H/OS-X-BrcmPatchRAM) because of an error-handling code added on top of [RehabMan's code.](https://github.com/RehabMan/OS-X-BrcmPatchRAM).

If you have a spare DW1830 card lying around with the same problem I have mentioned, do give this a try!

**Comment by thiscodedbox** [comment]
For what it's worth, I had a similar issue, and I've taped the pins in the past, but this worked for me:

I turned off (unchecked) the option in the BIOS to turn on/off Wifi and Bluetooth with the keyboard - I think it disabled the functionality of the PrtScr button that turns on airplane mode and I didn't have to tape the pins, started working fine.

BIOS 1.9.0 XPS13 9350 i7-6560u 16GB DW1830
