### ISSUE TITLE
Not working on XPS 13 9350 BIOS 1.10

### ISSUE THREAD

**Issue by VGerris** [hackintosh-stuff/XPS9350-macOS#8]
I'm unable to boot with my XPS 13 9350, QHD touch screen, 8 GB and 6200 CPU.
BIOS is latest, 1.10. I have a DW1820 wifi card built in. Issue is that it keeps printing something about Core Framework not starting with Mojave. 
I can post more details soon. None of the equivalent git repos worked unfortunately.

**Comment by Xerz** [comment]
Hi. 

Particular DW1820 installed in 9350 is known to be problematic. You need to replace it (with 1560 or 1830, for example). Here is more info (DanielKng also says that disabling both BT and Wi-Fi is OK to boot)
https://github.com/syscl/XPS9350-macOS/issues/222#issuecomment-478294407

Offtopic: i have got my 1820 from the laptop working on High Sierra **on Z370 desktop**, but it wasn't easy (googled 1820 on tonymacx86). On the desktop it atleast allows to boot into system with random freezes after 10-50 minutes, which can be 'fixed' (but someone says that after the fix CPU load is high all the time, mine is OK). I didn't manage to get bluetooth working stable after reboot (only cold boot).

The laptop even fails to boot with this card installed, so i didn't try get it working and replaced it with DW1560.

**Comment by VGerris** [comment]
Thank you for the quick response. The problem wasn't the wifi card initially, although it gave kernel panic when I didn't disable it. It turned out to be strange issue having to do with the creation of the USB. I redid it and it worked. 
The replacement wifi cards are a bit steeply priced I think, so I'll make an effort with the 1820 first, maybe I have 'the good version' :). Thank you for your contribution and support, I can close this ticket.

**Comment by x4080** [comment]
@VGerris can you boot into install disk? I did but keyboard and trackpad is not functioning, when using usb mouse it works
